AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'spec/fixtures/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  UseHashRocketsWithSymbolValues: true

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*_spec.rb'
