language: ruby
rvm:
  - 2.3.0
services:
  - postgresql
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database voltmobi_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - rake db:migrate RAILS_ENV=test